### ISSUE TITLE
Test suite doesn't build with servant 0.18.2

### ISSUE THREAD

**Issue by felixonmars** [haskell-servant/servant-swagger#129]
```
Preprocessing test suite 'spec' for servant-swagger-1.1.10..
Building test suite 'spec' for servant-swagger-1.1.10..
[1 of 2] Compiling Servant.SwaggerSpec ( test/Servant/SwaggerSpec.hs, dist/build/spec/spec-tmp/Servant/SwaggerSpec.dyn_o )

test/Servant/SwaggerSpec.hs:44:14: error:
    • No instance for (HasSwagger
                         (Fragment Int :> Servant.Test.ComprehensiveAPI.GET))
        arising from a use of ‘toSwagger’
    • In the expression: toSwagger comprehensiveAPI
      In an equation for ‘_x’: _x = toSwagger comprehensiveAPI
      In the second argument of ‘($)’, namely
        ‘do let _x = toSwagger comprehensiveAPI
            True `shouldBe` True’
   |
44 |     let _x = toSwagger comprehensiveAPI
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dmjio** [comment]
https://github.com/haskell-servant/servant-swagger/commit/cce6bf064e01ade21a7a8f283beca41595792446
